POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "url": "https://hiidenkivenpuutarhassa.blogspot.com/",
    "title": "Hiidenkiven puutarhassa",
    "author": "Minna Heinonen",
    "userId": "604b2402c86ca98bf8cc6926",
    "likes": 205
}
